version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_USER=user
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database
    app:
        build: .
        command: /srv/run.sh
        tty: true
        volumes:
            - .:/srv
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
        ports:
            - "3031:3031"
        user: "${UID}:${GID}"
        depends_on:
            - db
    nginx:
        image: nginx:1.16.0
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/.htpasswd:/etc/nginx/.htpasswd
            - .:/srv
        links:
            - app
        ports:
            - "0.0.0.0:80:80"

volumes:
    .:

